const express = require("express")
const cors = require("cors")
const routerUsers = require("./router/user")
const routerTrain = require("./router/train")
const routerAdmin = require("./router/admin")
const routertktbook = require("./router/tktbook")
const app = express()
app.use(express.json())
app.use(cors("*"))
app.use(express.static("uploads"))
app.use("/train", routerTrain)
app.use("/user", routerUsers)
app.use("/admin", routerAdmin)
app.use("/tktbook",routertktbook)
app.listen(4000, "0.0.0.0", () => {
  console.log("Server started at port 4000")
})
